INSERT INTO contacts (id, linkedin_url, first_name, last_name, position, location, company_name, company_id_linkedin, entreprise_id, years_in_position, months_in_position, years_in_company, months_in_company, id_url_linkedin, summary, title_description, connection_degree, is_premium, is_open_link, shared_connections_count, profile_image_url, default_profile_url, query) VALUES
&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('04cccf06-abf1-4197-b733-392dc3643723', 'https://www.linkedin.com/sales/lead/ACwAAAQ7szMBtPd-uCaJRYOddzzyjGj0LdEzl5M,NAME_SEARCH,8zlP', 'Emeric', 'Gatelier', 'Global Head of Design', 'Paris, Île-de-France, France', 'Edenred', '3057', (SELECT id FROM entreprises WHERE company_id_linkedin = '3057' LIMIT 1),
, 3, 11, 4, 9, 'ACwAAAQ7szMBtPd-uCaJRYOddzzyjGj0LdEzl5M', 'Defining group design vision and infusing our 45 @Edenred operational countries.', NULL, '2nd', False, False, 14, 'https://media.licdn.com/dms/image/v2/D4E03AQG343mH4kEdCw/profile-displayphoto-crop_800_800/B4EZns1gf.KYAI-/0/1760615074563?e=1765411200&v=beta&t=gjrgspqa9BjRWyKKvPfUbUpcZiL6ONpvmE_aioVODdE', 'https://linkedin.com/in/emericgatelier', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0))))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED))))),
&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('53a8dc86-2362-4d0a-ac01-c7e1bddca007', 'https://www.linkedin.com/sales/lead/ACwAAAYdpZ8Bhbx8H8unQIR9e79m-3JrpsvfUDE,NAME_SEARCH,WmC0', 'Sébastien', 'Altounian', 'Head of Product | Data & AI', 'Paris, Île-de-France, France', 'Thiga', '4998677', (SELECT id FROM entreprises WHERE company_id_linkedin = '4998677' LIMIT 1),
, 2, 1, 2, 1, 'ACwAAAYdpZ8Bhbx8H8unQIR9e79m-3JrpsvfUDE', 'Former entrepreneur, experienced manager, dedicated to digitalizing SMBs and evangelizing the implementation of AI. Strong skills in product and change management. 
Strategic vision | Organization | Communication', '- Audit and optimize organizations 
- Leverage data & AI to foster productivity 
- Help our clients deliver high-value products', '2nd', False, False, 2, 'https://media.licdn.com/dms/image/v2/D4E03AQEaUjcdbduX5g/profile-displayphoto-crop_800_800/B4EZj11XfbGcAI-/0/1756471067453?e=1765411200&v=beta&t=csuc_5IVp9N3lrwj9bUaEdvzPFdI8NCYs87Dwkc0CeI', 'https://linkedin.com/in/sebastien-altounian', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0))))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED))))),
&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('25daeda8-7d3a-4d9f-a3b3-f59995f30361', 'https://www.linkedin.com/sales/lead/ACwAAAblTZsBHXzthK1vlKQ5_x2vpjbLsFwpGA4,NAME_SEARCH,fO-H', 'Kévin', 'DRENO', 'Head of Engineering', 'Île-de-France, France', 'Kactus', '11049381', (SELECT id FROM entreprises WHERE company_id_linkedin = '11049381' LIMIT 1),
, 3, 7, 3, 7, 'ACwAAAblTZsBHXzthK1vlKQ5_x2vpjbLsFwpGA4', 'Entrepreneur | CTO | Management d''équipes | Enseignant à #SUPDEWEB', NULL, '2nd', False, False, 20, 'https://media.licdn.com/dms/image/v2/D4E03AQFLq7Z5a0Yr_g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1680591251324?e=1765411200&v=beta&t=UwbI6qIFTW8arDsNDOLGK2IKJz4L4xa_YwAoMmHlDwE', 'https://linkedin.com/in/kevindreno', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0))))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED))))),
&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('c93eb844-ce4c-4333-b64e-123a986a1cea', 'https://www.linkedin.com/sales/lead/ACwAAAb-1hYBwfUXvHD-aEV27RT6DguRAgwCWXg,NAME_SEARCH,pq0U', 'Riyad', 'LOUNISSI', 'Head of UX & Innovation - Head of product, DATA & Transformation durable', 'Rueil-Malmaison, Île-de-France, France', 'TNP Consultants', '250399', (SELECT id FROM entreprises WHERE company_id_linkedin = '250399' LIMIT 1),
, 3, 3, 3, 3, 'ACwAAAb-1hYBwfUXvHD-aEV27RT6DguRAgwCWXg', '1) Direction Conseil (cadrage stratégique, transformation digitale,  accompagnement et conseil auprès des clients, des équipes commerciales et des équipes projets interne)

Directeur eXperience Center by CGI

2) Opérationnelle (direction de projet, animation d''ateliers, production de livrables orientés conseil, évangélisation, Management de l''équipe, pilotage transverse des projets...) 

3) Business (support au commerce, fidélisation et relation clients, identification de nouvelles opportunités, qualification du besoin, conception de nouvelles offres et rédaction des propositions commerciales sur mesure).

4) Recrutement des profils (sourcing, qualification et recrutement des profils...)

5) Enseignement, Formation, Coaching et partenariats avec des écoles & universités
 - ECV Digital
- Ecole Multimedia
- IESA Multimédia
- EPF
- Telecom Sud Paris

', NULL, '2nd', True, True, 199, 'https://media.licdn.com/dms/image/v2/D4E03AQEl322LJ3csJw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1693917713859?e=1765411200&v=beta&t=gaasPjRZjjHX8f9ifUTDUFNfIk4Qfc3n1fAYidNvhgw', 'https://linkedin.com/in/riyad-lounissi-15a37b33', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('c384392c-1310-4785-ac09-f0134fa5ec0e', 'https://www.linkedin.com/sales/lead/ACwAAAhdgzMBT4KAxdjIeEBi1mbGjxMGDpEw-gU,NAME_SEARCH,K_Ht', 'Laurent', 'Debuchy', 'Head of User Experience', 'Paris, Île-de-France, France', 'Club Med', '163115', (SELECT id FROM entreprises WHERE company_id_linkedin = '163115' LIMIT 1), 8, 3, 8, 3, 'ACwAAAhdgzMBT4KAxdjIeEBi1mbGjxMGDpEw-gU', 'Dans les internets depuis 1997... 
 
Avec une expérience de plus de 25 ans dans les domaines de la communication Je suis un professionnel expérimenté en UX/UI avec une solide expertise en stratégie digitale et direction artistique. 

De part mon parcours J’ai une expérience approfondie dans le management d’équipes créatives et techniques, ainsi que dans la coordination internationale de projets complexes.

Actuellement Head of User Experience chez Club Med, je définie l’exécution de visions stratégiques aussi bien B2C que B2B centrées sur l’utilisateur, tout en assurant la cohérence des parcours UX sur l''ensemble de mon scope.

J’apporte une valeur ajoutée significative à chaque étape du cycle de vie d’un projet, de la conception stratégique à l’exécution opérationnelle.

Je fais ou j''ai pu faire : 
 | Management d''équipes - Créative / Technique / Projet (de 3 à 15 personnes)
 | Direction Artistique et design chez l''annonceur ou en agence.
 | Pilotage de phase de discovery, design thinking, Atelier d''idéation…
 | Gestion de projet Web - E-commerce / Méthodes Agile, Scrum, Cycle en V…
 | Gestion de projet Mobile (App ou Site)
 | Gestion de projet CRM
 | Gestion grands comptes 

Expériences : React | iOS | Demandware | Hybris | Magento | Drupal | Neolane |  Wordpress | ... sont des mots familiers

Figma | Sketch | Content Square | invision,craft & cie | Suite Adobe | Axure | Merlin | le sont aussi', 'Je suis en charge des équipes UX et UI qui gèrent les aspects B2C, B2B et app.
Nous assurons la delivery des fonctionnalités selon les process de méthodologie UX (Data driven, Discovery, test & learn…) pour l''ensemble des unités
Nous pilotons également une bibliothéque partagée qui nous permet d''assurer une expérience commune optimale pour tous nos médias.

| En B2C :
Mes équipes travaillent sur le site E-commerce disponibles sur 40 locales et 36 langues.
https://www.clubmed.fr

| En B2B : 
Mes équipes prennent en charge les interfaces de commandes destinés aux vendeurs directs et indirects

| Application mobile : 
Mes équipes conçoivent et réalisent l''UX et l''UI nécessaire à une expérience voyage optimale en en village (informationnelle et commerciale)', '2nd', False, False, 21, 'https://media.licdn.com/dms/image/v2/C4D03AQE0_t9NqK1XTA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1590679171531?e=1765411200&v=beta&t=chEHcVvkGVpRH8xCgVB8wgqVFnxpNfDNgPrLvwnu_xg', 'https://linkedin.com/in/laurent-debuchy-a170023b', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('45b8d0c4-0447-4a16-b7cf-07613af70ad1', 'https://www.linkedin.com/sales/lead/ACwAAAnWLsUBcTNqBNE7r9aSaXzKumxRj85BvUk,NAME_SEARCH,XKjT', 'Jules', 'Vagner', 'Head of Sales', 'Orléans, Centre-Val de Loire, France', 'Heuritech', '3518513', (SELECT id FROM entreprises WHERE company_id_linkedin = '3518513' LIMIT 1), 1, 11, 3, 0, 'ACwAAAnWLsUBcTNqBNE7r9aSaXzKumxRj85BvUk', 'With 10 years of experience in complex software sales, I help companies turn AI and data into business impact.

As Head of Sales at Heuritech, I lead commercial strategy for a cutting-edge SaaS platform that uses computer vision to predict fashion trends and optimize production decisions. My background includes scaling sales in deep tech environments such as AnotherBrain (AI for Quality Control) and Enovacom (Medical Imaging & e-Health).

I combine a solid technical understanding of AI systems with a pragmatic approach to business growth, from go-to-market execution to enterprise deal negotiation.

Beyond tech, I’m the Founder and President of Objectif Zéro Plastique, a French NGO that is active around the #PlasticsTreaty negotiations. I also coordinate the Francophonie Zéro Plastique coalition and sit on the board of the “Fresque du Plastique”.

I regularly give talks for companies, public institutions and NGOs on plastic pollution, AI, sustainability and collective action.

Curious, impact-driven and solution-oriented, I believe innovation should serve both performance and purpose.', 'As Head of Sales, I lead the commercial strategy of Heuritech, a fashion-tech SaaS platform using computer vision to predict trends and optimize production decisions.

Key achievements
• Scaled the client acquisition engine, resulting in 6x more new customers closed YoY, from emerging brands to enterprise groups.
• Built and structured the new business organisation across Fashion, Luxury and Sports verticals
• Closed mid-market and enterprise deals with European, US, APAC brands & OEM
• Improved sales velocity by redesigning our qualification framework (from 1 year to a couple of months on avg)
• Strengthened collaboration with Product teams to push new customer-centric capabilities
• Led strategic accounts with exec-level stakeholders (C-suite, VP Merchandising, VP Data, Innovation Directors)

Impact
• Closed several multi-year deals, including a flagship 3-year contract with a major OEM and multiple 2-year agreements that strengthened long-term revenue visibility
• Drove the expansion toward the OEM vertical and secured our first clients in India.
• Helped clients reduce overstock through AI-driven trend and demand insights
• Strengthened sales efficiency by doubling qualified outbound meetings and improving outbound-to-opportunity conversion', '2nd', True, True, 190, 'https://media.licdn.com/dms/image/v2/D4D03AQEoDhE89jXCMw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1714589522890?e=1765411200&v=beta&t=_AXGXEJiIYGfc_263cNGTTPUxhfAZEW5J2fpLrxqS3w', 'https://linkedin.com/in/julesvagner', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('9e098eb9-4990-47b0-97bc-6d2d63327a08', 'https://www.linkedin.com/sales/lead/ACwAAAoww1UBuYriHqzmX1Clyt20bCtdbcN_OO0,NAME_SEARCH,-F_b', 'Grégoire', 'Kodjabeykian', 'Head of data', 'Paris, Île-de-France, France', 'CHANEL', '162993', (SELECT id FROM entreprises WHERE company_id_linkedin = '162993' LIMIT 1), 3, 6, 6, 0, 'ACwAAAoww1UBuYriHqzmX1Clyt20bCtdbcN_OO0', NULL, NULL, '2nd', False, False, 10, 'https://media.licdn.com/dms/image/v2/C4D03AQHdKovSvbFmzQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1571095235498?e=1765411200&v=beta&t=wowaS9wNigKc-BqkeIkRJ-VcictRA0OmwZyM6LZGVcY', 'https://linkedin.com/in/gregoire-kodja', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('6c4f381d-22a1-457b-a359-355264eac4a3', 'https://www.linkedin.com/sales/lead/ACwAAAt6kKYB5GVoysJ4rSku-3Dx59Dda629AkM,NAME_SEARCH,MO7_', 'Erik', 'Le Roux', 'Head of Marketing & Communication | Lead Luxury Division - Steigenberger Icons Hotels', 'Paris, Île-de-France, France', 'H World International', '102634708', (SELECT id FROM entreprises WHERE company_id_linkedin = '102634708' LIMIT 1), 1, 11, 1, 11, 'ACwAAAt6kKYB5GVoysJ4rSku-3Dx59Dda629AkM', 'With 8 years’ experience in luxury within prestigious Maisons, I have developed strong skills to lead and manage projects to success. Business oriented with creative mindset I love taking up new challenges. My passion and my entrepreneurial spirit allow me to develop disruptive strategies. 
Hard worker, agile with an open-mind I am looking forward to emphasising my leadership to drive your strategy beyond limits.   
I have taken the lead on the launch of 3 niche fragrance brands in Paris and a full rebranding of a 5 Stars Superior (Palace rank) Hotel chain in Europe with outstanding results.

Do you want to achieve big things? 

+336 89 14 06 08 
leroux_erik@yahoo.fr', 'Position a premier luxury hospitality brand as the destination of choice worldwide. Leading brand desirability and market presence through refined digital, PR, and omnichannel strategies. Guiding a talented team across Europe to craft exceptional guest experiences, drive conversions, and build enduring brand prestige across all touchpoints.

Portfolio management of 6 properties - 5 Stars Superior Hotels | Palace', '2nd', False, False, 11, 'https://media.licdn.com/dms/image/v2/D4E03AQGHyOThUZfNcQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1689159821899?e=1765411200&v=beta&t=9H5feMgRCrnXZ1l0c2vL4VfqQmXRGujqxKaP0ko95fQ', 'https://linkedin.com/in/erik-leroux', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('090c63c8-0971-4345-a27d-a528ba976082', 'https://www.linkedin.com/sales/lead/ACwAAAx79PEBZF8akCbo8ocqW-ZF4cjIE1QioSE,NAME_SEARCH,MHmB', 'Laurent', 'Boyenval', 'Founder - Startup advisor & Headhunter - Growth engineer, talent acquisition', 'Paris, Île-de-France, France', 'Pareto Agency - France', '72102349', (SELECT id FROM entreprises WHERE company_id_linkedin = '72102349' LIMIT 1), 5, 7, 5, 7, 'ACwAAAx79PEBZF8akCbo8ocqW-ZF4cjIE1QioSE', '10+ years of experience in entrepreneurship and growth. 
Doer and builder: focused on sustainable growth. Forget about hacks and shortcuts.

Ex-entrepreneur (€2M/year), I support founders and entrepreneurs from Seed to Series A in 3 categories:
• Startup Advisor for Founders
• Growth Engineer
• Headhunter

Skills: 
• Launching new products/services within months
• Lead generation specialist for B2B and B2C
• Building with low-code solutions

Fun facts about me:
• A large US corporation almost acquired my previous startup, but the deal was canceled and we ran out of money.
• I opened 8 countries in 6 months when everyone said "it''s impossible."
• For a startup with 100 employees, I doubled lead generation in 6 months with the same budget and quality, which led to the sales team working every weekend.
• I discovered entrepreneurship at 14, with no prior inclination, by coding my first website from scratch and earning several thousand euros.
• While I was a broke student, I refused my first full-time job at a large corporation as an engineer to join a SaaS startup with a low salary that participated in YCombinator.', 'Ex-entrepreneur, I support founders and entrepreneurs from seed to Series A in 3 categories:

• Startup Mentor for founders (B2B and B2C): launching new business activities,
business models, business plans, pith deck, fundraising with business angels, shareholders'' agreements, pricing, go-to-market strategies, revenue optimization, opening new countries, B2B partnerships and corporate deals
• Growth Engineer: Outbound marketing, inbound marketing, data analysis, low code solutions
• Headhunter: Hiring A-players for C-level and "Head of" roles, in tech/marketing/OPS/sales

Some of my clients:
Bulldozair: €5M fundraised, SaaS B2B, YCombinator S16, acquired
Karmen: €22M fundraised, fintech
Legalplace: €27M fundraised, legaltech
Tracktor: €15M fundraised, construction
Collective.work: €7M fundraised (Hexa / eFounders), SaaS for freelancers
Je Rêve d''une Maison: €1M fundraised, proptech, acquired
Upstone: Bootstrapped, crowdfunding in real estate, acquired
Product-live: Bootstrapped, SaaS for retailers and e-commerce

Growth Engineer Skills:
• Outbound Marketing: cold emailing, scraping, landing pages
• Inbound Marketing: Content strategy, SEO
• Paid Acquisition (SEA, >€1M budget): Google Ads, Facebook Ads, LinkedIn Ads
• Data: funnel optimization, revenue optimization, Google Analytics, database
• Sales: sales OPS, process, team coaching
• Marketing Automation: CRM, HubSpot, Pipedrive, Intercom
• Automation and OPS: setup and scaling, Zapier expert
• Low Code adept
Stack: Lemlist, Outreach, Oncrawl, Semrush, Ahrefs, Figma, Webflow, Chargebee, Hotjar, Zapier, Heap, Airtable, Bubble, Intercom, Segment, n8n, Customer.io, Mixpanel, Amplitude

Headhunter and Talent Acquisition skills:
• Using Advanced Techniques: X-ray, data scraping, Google Dorks, and CSE.
• Engagement with high personalization: over a 50% reply rate.
• Pitching Your Startup: Persuading top talent to join your team.
At the end of the process, you will have 3 candidates that match your needs.', '2nd', True, True, 83, 'https://media.licdn.com/dms/image/v2/C5603AQHUtUkReoLERg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1566564540992?e=1765411200&v=beta&t=K0WbYpFuvKPWoV791MlTtCX_y_bie8QlLnvw-1t6OCI', 'https://linkedin.com/in/laurentboyenval', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('161af357-386c-4cb9-adce-055462c9d0e1', 'https://www.linkedin.com/sales/lead/ACwAAAyJPW8B3ApcOho2ofhce6CHmdFheliyyl8,NAME_SEARCH,3sRX', 'Nicolas', 'Stouls', 'Head of Product Management', 'Paris, Île-de-France, France', 'Ceetiz', '3486843', (SELECT id FROM entreprises WHERE company_id_linkedin = '3486843' LIMIT 1), 5, 3, 5, 3, 'ACwAAAyJPW8B3ApcOho2ofhce6CHmdFheliyyl8', 'Head of Product  @Ceetiz
Former PM @Veepee @SNCF Connect @Club Med @Société Générale', NULL, '2nd', False, False, 12, 'https://media.licdn.com/dms/image/v2/C5103AQGDShYctcEgzg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1517379375486?e=1765411200&v=beta&t=ZOQ67c90zyxWKlUjwCjtFPJ6OpLcc15OUDZVhXtYp90', 'https://linkedin.com/in/stoulsnicolas', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('45c0d275-467a-409b-9e46-749a55810b70', 'https://www.linkedin.com/sales/lead/ACwAAAygVJ4BYPgZ-fGsCNwskkP8iJ_3hVLdfbw,NAME_SEARCH,Bk9a', 'Amaury', 'Caulliez', 'Head of commercial animation France', 'Roubaix, Hauts-de-France, France', 'La Redoute', '9971', (SELECT id FROM entreprises WHERE company_id_linkedin = '9971' LIMIT 1), 1, 3, 2, 5, 'ACwAAAygVJ4BYPgZ-fGsCNwskkP8iJ_3hVLdfbw', '9 années d’expérience dans les métiers du digital et l''e-commerce me permettent aujourd''hui de gérer des projets et des équipes dans un contexte hyper-concurrentiel.

Dynamique et volontaire, je suis quelqu’un d''enthousiaste, créatif et curieux. J’accorde de l’importance à l’innovation, dans une société digitalisée où les modes de consommation évoluent très rapidement, mon sens de l''adaptation est un atout.

Mes domaines de compétences sont :
▪ e-Merchandising
▪ Analyse des performances (web analytics)
▪ Refonte de sites Internet ▪ Optimisation du parcours client (A/B Testing)
▪ Optimisation des moteurs de recherche (OMR) ▪ Stratégies d''acquisition SEO / SEA
▪ Stratégies d''activation digitale ▪ Déploiement, utilisation et évolution de CMS
▪ Mise en place de stratégie multicanal ▪ Trade marketing (shop in shop)
▪ Pilotage de projets web et mobile ▪ Gestion de projets
▪ Briefing des créations display
▪ Leadership ▪ Management', NULL, '2nd', False, False, 48, 'https://media.licdn.com/dms/image/v2/C5603AQFsQBkcVifr5g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1564567054357?e=1765411200&v=beta&t=duNoMxVNZXsuG-n7Mp2gPsbuOfPKnNoKncUKfT0TxJU', 'https://linkedin.com/in/amaury-caulliez-166b395a', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('3b894519-c34b-4658-a77e-f7067137d8df', 'https://www.linkedin.com/sales/lead/ACwAAA1WoggBSCxwiy8nqvauNNfhBQ4KEWR8cqw,NAME_SEARCH,TFbU', 'Adam', 'Batlaj', 'Head of Product Ops - TF1+', 'Paris, Île-de-France, France', 'Groupe TF1', '6240', (SELECT id FROM entreprises WHERE company_id_linkedin = '6240' LIMIT 1), 0, 9, 0, 9, 'ACwAAA1WoggBSCxwiy8nqvauNNfhBQ4KEWR8cqw', NULL, NULL, '2nd', False, False, 11, 'https://media.licdn.com/dms/image/v2/C5603AQFDjPKWjCDo6g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1537121351584?e=1765411200&v=beta&t=tCmDSOm-LbKdsryUYCgbhXiohcLLwOldxqA1s-g-zes', 'https://linkedin.com/in/adambatlaj', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('01bb5763-67ab-478b-a538-1b3fceb37fba', 'https://www.linkedin.com/sales/lead/ACwAAA4hAAkBgjcdKygFukptJ19zO4I6RS0_ARY,NAME_SEARCH,MhQG', 'Rémy', 'VILLECROZE', 'Head of Data Analytics', 'Annecy, Auvergne-Rhône-Alpes, France', 'Worldia', '2980106', (SELECT id FROM entreprises WHERE company_id_linkedin = '2980106' LIMIT 1), 2, 11, 2, 11, 'ACwAAA4hAAkBgjcdKygFukptJ19zO4I6RS0_ARY', NULL, NULL, '2nd', False, False, 5, 'https://media.licdn.com/dms/image/v2/C5603AQF3juI6hTB1Dg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1517355288193?e=1765411200&v=beta&t=HqLLSPVac-C59F8xHFJ6y0WnK-Yn8MB_s9UWhDLbEjA', 'https://linkedin.com/in/r%C3%A9my-villecroze-0b547667', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('9f52701f-88e2-4994-9cbb-6263c7538b76', 'https://www.linkedin.com/sales/lead/ACwAAA5YyfIB1Gw7p9hH7lSSxW6b3gaecAa_P_U,NAME_SEARCH,iTgP', 'Sylvain', 'Bontoux', 'Head of Design', 'Paris, Île-de-France, France', 'THOM', '46043163', (SELECT id FROM entreprises WHERE company_id_linkedin = '46043163' LIMIT 1), 1, 2, 1, 2, 'ACwAAA5YyfIB1Gw7p9hH7lSSxW6b3gaecAa_P_U', 'Senior UX designer / Researcher & UX strategist, j''interviens aussi bien chez les grands comptes qu''en start-up.
Faites appel à moi pour :

💡 Vous aider à construire votre stratégie UX, intervenir dans le processus d’innovation et valider des concepts à forte valeur ajoutée

🔎 Construire et conduire votre recherche, cartographier l''expérience de vos utilisateurs et votre eco-système ; piloter les tests utilisateurs pour réunir des feedbacks et optimiser vos produits et services

💬 Animer des ateliers d’idéation et co-design avec vos utilisateurs et vos collaborateurs

🖥️ Matérialiser vos concepts en interface (app, site web, application métier, logiciel, objet connecté, etc.)

Mes références : Orange Bank / Evaneos / SNCF / Banque Postale / Roche Diabetes Cares / Banque Populaire / Europassistance / Ministère De La Défense / Thecamp / ...

N''hésitez pas à me contacter pour que nous échangions ensemble autour d''un café ! ☕️', 'Pilotage de la stratégie UX et management du pôle design pour accompagner la transformation digitale du groupe sur 3 marchés (France, Italie, Allemagne).
• Mise en place d’une méthodologie centrée utilisateur pour comprendre les besoins et comportements
• Traduction des insights en parcours optimisés sur les canaux e-commerce, retail et CRM
• Définition et suivi d’indicateurs UX pour mesurer la performance et guider les itérations
• Encadrement des designers, structuration de l’équipe et diffusion d’une culture design transverse aux marques', '2nd', False, False, 38, 'https://media.licdn.com/dms/image/v2/D4E03AQHxS2PmHerrUw/profile-displayphoto-shrink_800_800/B4EZTWIbnzGgAc-/0/1738759322468?e=1765411200&v=beta&t=HhaXE0hmACH-xjfBD1b1wTWv6h9_f_2sPgTukzxHc6A', 'https://linkedin.com/in/sylvainbontoux', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('c137348a-cc21-4ffe-9588-5fa9f6d7795f', 'https://www.linkedin.com/sales/lead/ACwAAA716ZgBU6T1WuypR73zTshPPrr39CnM3Rs,NAME_SEARCH,essr', 'Florian', 'Chamare', 'Head of Programmatic Trading Europe', 'France', 'Locala', '2982107', (SELECT id FROM entreprises WHERE company_id_linkedin = '2982107' LIMIT 1), 1, 6, 1, 6, 'ACwAAA716ZgBU6T1WuypR73zTshPPrr39CnM3Rs', NULL, NULL, '2nd', False, False, 20, 'https://media.licdn.com/dms/image/v2/C5603AQGHSJRMKlliNQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1517491195731?e=1765411200&v=beta&t=_gy-HtXTvtVSOzAKRlMF32QeO80vSvxizgOHmUN15_Q', 'https://linkedin.com/in/florianchamare', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('6ccd45c9-a89c-4329-92a0-b876a1eabfef', 'https://www.linkedin.com/sales/lead/ACwAABEfZWEBsVS6uVxalDQAmHHfAq3kteNtGLs,NAME_SEARCH,Zfnl', 'Emilie', 'Larose', 'Head of Experience Strategy & Client Insights (entité conseil)', 'Paris, Île-de-France, France', 'Ippon Technologies', '20908', (SELECT id FROM entreprises WHERE company_id_linkedin = '20908' LIMIT 1), 1, 9, 3, 3, 'ACwAABEfZWEBsVS6uVxalDQAmHHfAq3kteNtGLs', 'Professionnelle du design avec plus de 12 ans d’expérience dans la construction et l’accompagnement d’équipes design. J’allie connaissance utilisateur, vision produit et enjeux business pour structurer des démarches efficaces et adaptées aux organisations. Spécialisée en recherche, design operations et conception d’expériences cohérentes, j’ai travaillé dans des environnements variés et exigeants (tech, mobilité, luxe). Mon objectif : mettre le design au service de décisions claires, utiles et durables.', 'Développement et commercialisation d’offres stratégiques autour de la connaissance client et de l’expérience. Accompagnement de clients grands comptes dans l’alignement entre insights consommateurs, innovation et performance business. Création d’une offre de Design Prospectif intégrant l’anticipation des usages et tendances clients.', '2nd', False, False, 55, 'https://media.licdn.com/dms/image/v2/D4E03AQF0YMA0CW5VsA/profile-displayphoto-crop_800_800/B4EZi_fA3sHIAI-/0/1755559237805?e=1765411200&v=beta&t=GRXSEgYJlkhCZEMk5l873iI7LZjSPRf5ffT97FPYNs8', 'https://linkedin.com/in/emilie-larose-42925880', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('5d91b903-529a-4578-8bfc-df977e17155e', 'https://www.linkedin.com/sales/lead/ACwAABGxs2cB5wZpQURMf83HF9mhgnPeRdHWr5Y,NAME_SEARCH,-LOj', 'Sivaranjiny', 'SIVA', 'Head of Marketing', 'Plaisir, Île-de-France, France', 'AxFlow France', '11035135', (SELECT id FROM entreprises WHERE company_id_linkedin = '11035135' LIMIT 1), 1, 8, 1, 8, 'ACwAABGxs2cB5wZpQURMf83HF9mhgnPeRdHWr5Y', '🎯 Marketing & Communication | Stratégie de Contenu | Engagement & Notoriété de Marque

Avec 5 ans d''expérience dans le marketing et la communication, je conçois et pilote des campagnes impactantes qui renforcent la visibilité des marques et engagent les audiences. Spécialisée en création de contenu, gestion des réseaux sociaux et communication interne/externe, j’aime développer des stratégies innovantes et captivantes.

Curieuse et créative, je puise mon inspiration dans mes passions : la cuisine, le cinéma et les voyages, qui m’aident à explorer de nouvelles idées et à les intégrer dans mes projets professionnels. Toujours en quête d’innovation, j’aime relever de nouveaux défis pour connecter les marques à leur public de manière authentique et percutante.

💬 Échangeons !', 'AxFlow est une entreprise familiale et indépendante, intégrée au groupe Axel Johnson International. Présent dans 33 pays à travers l’Europe, l’Afrique du Sud, l’Australie et la Nouvelle-Zélande, le groupe AxFlow bénéficie d’un fort ancrage international.
AxFlow France, filiale à 100 % du groupe, propose une offre complète et haut de gamme d’équipements destinés à la gestion des fluides.

- Gestion du budget et des ressources disponibles
- Conception & préparation les campagnes marketing
- Animation du site internet et optimisation du référencement naturel et payant
- Gestion des relations presse et organisation des salons professionnels
- Assurer la communication interne via des newsletters et l’intranet
- Élaboration et mis en œuvre des stratégies de lancement de produits
- Superviser le plan marketing pour promouvoir les produits et services
- Accompagnement de la force de vente dans l’identification des clients cibles et de leurs besoins
- Superviser la création et le suivi des supports visuels d’aide à la vente, tels que catalogues, encarts web et contenus multimédia', '2nd', False, False, 12, 'https://media.licdn.com/dms/image/v2/C5603AQFIGhulwf_eMg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1634544734755?e=1765411200&v=beta&t=lSmoKELAlxZWsDMy_TnZWKTp9Po2TFqkAKKGukr-gVM', 'https://linkedin.com/in/ssivaranjiny', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('abd47ff7-34e6-44a0-bde8-78d27e949f41', 'https://www.linkedin.com/sales/lead/ACwAABI6qf0BFJw7F53OOm_pgDmgsxucf-wdWlE,NAME_SEARCH,4r_a', 'Antoine', 'Baltenweck', 'Head of Product', 'Paris, Île-de-France, France', 'Fnac Darty', '25852100', (SELECT id FROM entreprises WHERE company_id_linkedin = '25852100' LIMIT 1), 0, 11, 6, 1, 'ACwAABI6qf0BFJw7F53OOm_pgDmgsxucf-wdWlE', NULL, 'Définition de la stratégie et des priorités
- Définir la vision et la stratégie à long terme pour le portefeuille de produits
- Arbitrer la roadmap et les sujets structurants
- Être responsable de la roadmap et garantir la sérénité des équipes
- Définir de vrais périmètres produits, reconnaissables par l''ensemble de l''entreprise basés sur la stratégie du groupe
	
Pilotage par la Valeur et KPIs
- Identifier les opportunités de développement et mise en place des plans d''action
- Participer à la définition des SLO de son périmètre et à leur mise en place avec les squads 
- Pilotage par la data pour défendre les résultats et prendre des décisions éclairées
- Suivre et faire évoluer les KPIs de ses équipes
- Aider les Product Owners à travailler le pilotage par la valeur

Business Partner
- Se positionner en tant que point référent auprès des métiers
- Descendre les messages pertinents auprès des équipes 
- Partager les réalisations et promouvoir le travail des équipes
- Défendre les choix de conception auprès des stakeholders 
- Remonter les problématiques rencontrés par les équipes auprès de la direction', '2nd', False, False, 104, 'https://media.licdn.com/dms/image/v2/C5603AQGsk2KmUPzm2A/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1587031513588?e=1765411200&v=beta&t=YB-gWtlLivU05LUIlU-s2E_k8X7Q2kqJN3YIw6aeoYs', 'https://linkedin.com/in/antoine-baltenweck', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('f28b0f79-0339-42b0-b380-f7140326756f', 'https://www.linkedin.com/sales/lead/ACwAABOs_V0BvxD6ByEhNWfJusZo5UauBTh3flo,NAME_SEARCH,xs-R', 'Valentine', 'Seguineau', 'Head of Media & Acquisition', 'Nantes, Pays de la Loire, France', 'We Like Travel', '2991302', (SELECT id FROM entreprises WHERE company_id_linkedin = '2991302' LIMIT 1), 2, 7, 2, 7, 'ACwAABOs_V0BvxD6ByEhNWfJusZo5UauBTh3flo', NULL, NULL, '2nd', True, False, 11, 'https://media.licdn.com/dms/image/v2/D4E03AQEYNh5ka4zh7g/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1695209175148?e=1765411200&v=beta&t=r1KJnyA50N5D7YKjz8btGr47V_xLv7Q7ILIhmUMD_yU', 'https://linkedin.com/in/valentineseguineau', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('1cd93790-c3ce-4e40-bc30-20d3dab16d1d', 'https://www.linkedin.com/sales/lead/ACwAABQcw1UBk6E5aenmjfemri-JqFBmLk_bxiw,NAME_SEARCH,EVTg', 'Guillaume', 'Guéroult', 'Head of Product', 'Paris, Île-de-France, France', 'Fnac Darty', '25852100', (SELECT id FROM entreprises WHERE company_id_linkedin = '25852100' LIMIT 1), 0, 10, 0, 10, 'ACwAABQcw1UBk6E5aenmjfemri-JqFBmLk_bxiw', '10-year experienced Product Manager & UX Designer. I craft innovative digital products that prioritize user experience and agility. My Design Ops background empowers teams to drive digital transformation.', NULL, '2nd', False, False, 5, 'https://media.licdn.com/dms/image/v2/D4E03AQGlCi_Zi-WWgA/profile-displayphoto-shrink_800_800/B4EZPUspB9HEAg-/0/1734440292974?e=1765411200&v=beta&t=O_ZvO5wk7mCfiBCGB8HxHvSw12NC3oqsd5MnUBYpr0g', 'https://linkedin.com/in/guillaumegueroult', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('0574e1b1-b628-402d-a008-60f1283999fd', 'https://www.linkedin.com/sales/lead/ACwAABbnUZcBgJ5VuET439zCU_0eyxXvVn5NKLc,NAME_SEARCH,wR3W', 'Nasser', 'ZEDIRI', 'Global Head of Digital Experience & Marketing Intelligence', 'Paris, Île-de-France, France', 'Stellantis', '66256333', (SELECT id FROM entreprises WHERE company_id_linkedin = '66256333' LIMIT 1), 1, 2, 3, 4, 'ACwAABbnUZcBgJ5VuET439zCU_0eyxXvVn5NKLc', 'Web analytics are the heart. But insights bring the soul.

#Adobe #AdobeSpecialist #AdobeExperienceMaker #AdobeAnalytics #AdobeLaunch #AdobeTarget #AdobeAudienceManager #AdobeExperienceCloud', NULL, '2nd', False, False, 5, 'https://media.licdn.com/dms/image/v2/D4E03AQF4Nqc7lzD56Q/profile-displayphoto-shrink_800_800/B4EZWgyEA4GgAc-/0/1742159233721?e=1765411200&v=beta&t=JtiJh2Goi1bACIr0LkNoZHIQMKKuxytBj23-QTHQ6eM', 'https://linkedin.com/in/nasreddine-zediri', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('b19245c7-8a23-4365-9b2d-bff5c8c8c84e', 'https://www.linkedin.com/sales/lead/ACwAABh0dv4ByrmPerMGt-swEnthKrr5weuNDqA,NAME_SEARCH,S_8U', 'Florian', 'Gauthey', 'Head of Growth', 'Paris, Île-de-France, France', 'Sowefund', '3534320', (SELECT id FROM entreprises WHERE company_id_linkedin = '3534320' LIMIT 1), 1, 6, 1, 6, 'ACwAABh0dv4ByrmPerMGt-swEnthKrr5weuNDqA', 'Head of Growth & Marketing de Sowefund, notre objectif : permettre au plus grand nombre de co-investir dans les start-ups et PME les plus prometteuses et innovantes.

Sowefund, pionnier et leader du co-investissement, rejoint le groupe Founders Future en 2023 et représente :
+250 sociétés financées
+300M€ dédiés aux entreprises de croissance
+4 000 employés dans les sociétés du portefeuille

Des succès de la French Tech comme Mon Petit Placement, Lydia, Yuka, ekWateur, Lunii, Teads, Agriloops, La marque en moins.

Par le passé, j’ai eu l’opportunité de contribuer à la croissance des revenus et au développement marketing de Nexity (Responsable Marketing & Digital France) et de Prello Group (15M€ levés - Head of Growth & Marketing).', 'En charge du Growth chez Sowefund : Marketing, Product & Sales

Stratégie marketing & growth : définition du positionnement, pilotage des stratégies d’acquisition paid (Google Ads, Meta Ads, partenariats) et organic (SEO, content, referral), optimisation des parcours utilisateurs, intégration d’outils IA / GPT pour accélérer la génération de leads et améliorer la conversion.

Product : définition et suivi de la roadmap produit, coordination des refontes web, lancement de nouvelles fonctionnalités, amélioration continue de l’UX/UI.

Sales : management de l’équipe, optimisation des process commerciaux, des cibles et des messages pour maximiser la collecte des levées de fonds 

Pilotage de la performance : structuration d’une approche data-driven, suivi et analyse des KPIs Growth, Marketing et Produit.

Coordination transverse : alignement des priorités Marketing, Product et Data avec les autres pôles pour maximiser l’impact business.', '2nd', False, False, 99, 'https://media.licdn.com/dms/image/v2/D4E03AQFYMdA_XrwqqQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1723640454576?e=1765411200&v=beta&t=JiZYbD6xiBUAygr7xphDDR0gg7IFy-0zG17-oHAIcKU', 'https://linkedin.com/in/floriangauthey', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('dd70e56f-5f9f-4410-a036-0ae4e2d723d5', 'https://www.linkedin.com/sales/lead/ACwAABj2ODcBUQ0R61RzWLS79fED9YrlUKVcMgA,NAME_SEARCH,WH71', 'Tonya', 'Ratiaray', 'Head of People France', 'Paris, Île-de-France, France', 'Electra', '71246795', (SELECT id FROM entreprises WHERE company_id_linkedin = '71246795' LIMIT 1), 0, 5, 2, 2, 'ACwAABj2ODcBUQ0R61RzWLS79fED9YrlUKVcMgA', NULL, NULL, '2nd', False, False, 25, 'https://media.licdn.com/dms/image/v2/D4E03AQGXBf6sMYSWFQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1709972978978?e=1765411200&v=beta&t=POx72CB7BODXqFsIVX7RkbjwNmrYsgSUslfGb6WTVkQ', 'https://linkedin.com/in/tonya-ratiaray-bb3302b8', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('63c78fd0-7215-474f-a65a-94455fd5b3ea', 'https://www.linkedin.com/sales/lead/ACwAAB-_lhYBFT0tB2-GKdzMksmXxnfzkrn_pBQ,NAME_SEARCH,AhG0', 'Alexandre Sevag', 'Cancioglu', 'Head of Sales and Account Management', 'Paris, Île-de-France, France', 'MyCompanyFiles', '2382036', (SELECT id FROM entreprises WHERE company_id_linkedin = '2382036' LIMIT 1), 0, 11, 5, 6, 'ACwAAB-_lhYBFT0tB2-GKdzMksmXxnfzkrn_pBQ', 'Commercial qui se consacre à aider les cabinets d''expertise comptable dans leur parcours de transformation digitale. 

En tant que responsable d''une équipe chez MyCompanyFiles, j''ai eu le privilège de travailler avec de nombreux cabinets au fil des années, en les accompagnant dans l''adoption d''une solution innovante pour leurs clients.

Cette expertise me permet de leur offrir des conseils avisés, en les aidant à simplifier et à automatiser leurs processus avec leur client et à se préparer à l''arrivée de la facturation électronique.

Si vous recherchez un partenaire pour vous accompagner dans votre transformation digitale et votre transition vers la facturation électronique, je serais ravi d''échanger avec vous et de discuter des possibilités de collaboration.', NULL, '2nd', False, False, 65, 'https://media.licdn.com/dms/image/v2/D4E03AQF1P6n90V5G8w/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1720005265124?e=1765411200&v=beta&t=bZY6q9Q7KkR8TWcCpvTkmRzplnTAF15Hr89irfSPJxg', 'https://linkedin.com/in/cancioglualexandre', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAABLNONcB1D6rRU--3oZ5G-IFLVk55HT3xmI%2Ctext%3AEndza%2520Djergaian%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('f1f5a1c7-bb47-4c80-8d7c-43e471af4ba3', 'https://www.linkedin.com/sales/lead/ACwAAABSUN8BMn0tsfFztrUnpPEWZo41NgqFh-M,NAME_SEARCH,QC13', 'Thomas', 'Lagrange', 'Head of Global Analytics', 'Colombes, Île-de-France, France', 'Euronext', '3829', (SELECT id FROM entreprises WHERE company_id_linkedin = '3829' LIMIT 1), 5, 1, 5, 1, 'ACwAAABSUN8BMn0tsfFztrUnpPEWZo41NgqFh-M', 'After a strong formative consulting journey, I have focused on my passion of building and running great digital products. For a couple years, I have tackled mobile apps, e-commerce platform and customer portals, from strategy definition to implementation with agile teams/squads. Lately I have embarked in the entrepreneurship journey creating Tail.ai to meet the challenges of conversational commerce with a smarter and more accessible product.
I''m always ready for new challenges ! 
', NULL, '2nd', False, False, 13, 'https://media.licdn.com/dms/image/v2/C4D03AQF9Z47S5B_dUQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1570004214646?e=1765411200&v=beta&t=JGh5eNwYk3z1uWm9dU6arOlu5Gpt-Fu0ncLIGGF1reI', 'https://linkedin.com/in/thomaslagrange', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('fda79d4c-88a2-40c3-9679-beea10fc8bb7', 'https://www.linkedin.com/sales/lead/ACwAAACw7CoBtVICksaYVd0p5urtLC1DZxJABTo,NAME_SEARCH,G01D', 'Fabrice', 'Arsicot', 'Head Of Digital', 'Paris, Île-de-France, France', 'WAT agency', '1424979', (SELECT id FROM entreprises WHERE company_id_linkedin = '1424979' LIMIT 1), 14, 8, 14, 8, 'ACwAAACw7CoBtVICksaYVd0p5urtLC1DZxJABTo', 'I''ve always had a keen interest in the digital world and its cultural mix. My academic and professional career has been characterised by total immersion in the digital world, starting with my first experience at Infogrames, a software publisher, then in a web agency, and finally by managing and developing the digital expertise centres within leading agencies such as Ligaris/BABEL and WAT.

Based on these experiences, I drive and advise companies in the integration of innovative digital solutions, focusing on user experience, design, content and technology while cultivating an integrated approach to address business, HR and brand issues.

As a fan and active participant in triathlon, I like to combine different practices that can be complementary. Beyond an initial technical reading of digital, I value an approach that encompasses a wide range of expertise. It''s a conviction that has enabled me to build leadership skills in managing teams and complex projects, developing offers and driving strategic partnerships, while remaining committed to a vision of digital that combines creativity and responsibility.

#Digital expertise #Strategic leadership #Ecosystem management #Performance measurement #Spirit of innovation #Team management #International and intercultural sensitivity', 'Management of the Digital division, digital strategy and eco-system, business development and digital offering, newbiz and customer management, partner network management and development, internal and external agency communications, P&L management.', '2nd', True, False, 15, 'https://media.licdn.com/dms/image/v2/D4E03AQEEEhRZw6UCjA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1664181952034?e=1765411200&v=beta&t=qsH6KwKFOtRm5RwFIw35RxyUNX1eZXBMb-jNSb9mTX8', 'https://linkedin.com/in/fabricearsicot', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('ac92cc5a-2844-4d02-ba78-e3bb3aa57275', 'https://www.linkedin.com/sales/lead/ACwAAAHBUgQB9qYPuKn_-c4H4lEYk_Whx9rBqTg,NAME_SEARCH,vwnf', 'Anne-Laure', 'JANVIER', 'Head of Data Management @Cooper Consumer Health Group', 'Paris, Île-de-France, France', 'Cooper Consumer Health', '25700287', (SELECT id FROM entreprises WHERE company_id_linkedin = '25700287' LIMIT 1), 1, 3, 1, 3, 'ACwAAAHBUgQB9qYPuKn_-c4H4lEYk_Whx9rBqTg', 'Accomplished digital & data leader driving business growth through data-driven strategies, marketing insights, and governance excellence. Skilled in leveraging data analytics, data science, and automation to enhance customer experience and product offerings, delivering measurable ROI.

Currently Head of Data Management for the group at Cooper Consumer Health, where I lead the development and execution of the company’s global data strategy, driving data governance, analytics, platform modernization, and fostering a data-driven culture to support business transformation.

With extensive experience across startups, large corporations, and mid-sized enterprises, I bring a proven ability to adapt and deliver in international, multi-sector contexts. Trusted advisor to senior executives, experienced in leading data governance, master data management, and complex change initiatives across global organizations including Servier, ENGIE, and Reed Exhibitions.

Awarded Oracle Partner of the Year 2019, certified Emerging Leader by Harvard Business Publishing, and passionate about building smarter, collaborative teams for long-term success.', 'Cooper Consumer Health is a leading European consumer healthcare player that develops, produces, and distributes a diverse range of OTC (over-the-counter) products with strong brands such as Valdispert, Oenobiol, Excilor, Vitascorbol, Lashilé, Betadine and many more.
Today, we have just lead an exciting M&A project and acquired a large OTC portfolio. This strategic move has expanded our footprint across key European markets such as France, Netherlands, Italy, Belgium, Spain and Portugal.
Through this strategic acquisition, combine with our historical footprint, the Group will continue to be a pioneer in the development, manufacturing, and distribution of a diverse array of over-the-counter products. 

I''m responsible for the creation of a new data management team, charged with advancing data governance practices and implementing them to support the group''s growth within the group''s IT department. 

Huge focus on:
--- Data Management & Data driven strategy
--- Data Governance & Data access and quality
--- Data Analytics & Data Visualization
--- Communication & Stakeholder engagement
---Problem-solving & decision making
--- Program & Project management', '2nd', False, False, 13, 'https://media.licdn.com/dms/image/v2/D4E03AQGgIQoOH5XB9w/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1696949614544?e=1765411200&v=beta&t=WjOQJP7ZL-a8ABYJUEhItzkBiLguTZp-_gdDULQRgxM', 'https://linkedin.com/in/annelaurejanvierregnier', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('0340aea1-e904-4df9-a9af-11a5a5ed637a', 'https://www.linkedin.com/sales/lead/ACwAAAJLfK0B_yoaZ-bjnj1JpIyJCjGw-WiFwFU,NAME_SEARCH,DnCE', 'Ornella', 'Ferrari', 'Head of HR', 'Lyon, Auvergne-Rhône-Alpes, France', 'INLOG', '117224', (SELECT id FROM entreprises WHERE company_id_linkedin = '117224' LIMIT 1), 0, 2, 0, 2, 'ACwAAAJLfK0B_yoaZ-bjnj1JpIyJCjGw-WiFwFU', NULL, NULL, '2nd', False, False, 23, NULL, 'https://linkedin.com/in/ornellaferrari', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('a33c0704-4d83-4b91-b1e1-4ae1fce7f6b5', 'https://www.linkedin.com/sales/lead/ACwAAALy-RgBYeMrOsJbuL1ZfWGQNrE1M7hgHQ0,NAME_SEARCH,Aa9P', 'Corentin', 'Daras', 'Head of Sales', 'France', 'Jamendo', '167452', (SELECT id FROM entreprises WHERE company_id_linkedin = '167452' LIMIT 1), 5, 10, 5, 10, 'ACwAAALy-RgBYeMrOsJbuL1ZfWGQNrE1M7hgHQ0', NULL, NULL, '2nd', False, False, 5, NULL, 'https://linkedin.com/in/corentindaras', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('28eee8b9-44f8-4f6c-a0c7-18c6769cb61d', 'https://www.linkedin.com/sales/lead/ACwAAAMeIhsBLGquOfpV3mVm_dqx9zxYhyi2o1Y,NAME_SEARCH,UEzg', 'Peter', 'S.', 'Head of Mechatronics Innovation', 'Châtillon, Île-de-France, France', 'BizLink Group', '4868419', (SELECT id FROM entreprises WHERE company_id_linkedin = '4868419' LIMIT 1), 3, 11, 3, 11, 'ACwAAAMeIhsBLGquOfpV3mVm_dqx9zxYhyi2o1Y', 'De formation ingénieur mécatronique à dominante mécanique, j''évolue depuis plus de 15 ans dans le domaine de la robotique médicale. J''ai participé au développement du robot ORION, un système de positionnement de patient à forte charge et haute précision, aujourd''hui certifié CE et FDA, déployé dans plus de 150 centres de radiothérapie dans le monde.

Aujourd''hui responsable du département Innovation Mécatronique, j''assure la coordination technique d''une équipe de développement tout en conservant une forte implication dans la conception et le développement produit. Depuis 2017, j''assure également un rôle de référent DevOps partiel pour les outils collaboratifs (JIRA, Confluence, PDM), et depuis 2015, celui de référent qualité/réglementaire (QA/RA) sur les aspects mécatroniques des dispositifs médicaux. 

https://healthcare.bizlinktech.com/products-services/medical-systems/patient-positioning-system/

Si mon profil vous intéresse, n''hésitez pas à me contacter.

Spécialités: Mécanique - Mécatronique - Robotique', '•	Management de l''équipe Innovation Mécatronique
•	Pilotage du développement d''articulations robotiques et de robots complets
•	Suivi de l''évolution du positionneur de patient ORION en vie série
•	Interface avec les départements software, électronique, qualité et production', '2nd', False, False, 1, 'https://media.licdn.com/dms/image/v2/D4E03AQHpfm3pebntzg/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1677145000889?e=1765411200&v=beta&t=q5z7cz_OMGty0PCtG54cqTmfmyg9lOIgxMlupOp1gaY', 'https://linkedin.com/in/peter-s-b3762515', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('98939297-72c2-4899-8a9f-42c25b6d5390', 'https://www.linkedin.com/sales/lead/ACwAAAOXXbABvIFLu7xUIuL2gHnOo90xJxrDR8c,NAME_SEARCH,Exbu', 'Adrien', 'Debbah', 'Head of Sales', 'Paris, Île-de-France, France', 'Alma', '18834371', (SELECT id FROM entreprises WHERE company_id_linkedin = '18834371' LIMIT 1), 3, 3, 4, 5, 'ACwAAAOXXbABvIFLu7xUIuL2gHnOo90xJxrDR8c', NULL, NULL, '2nd', False, False, 41, 'https://media.licdn.com/dms/image/v2/D4E03AQHiJYVvXqN3ng/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1726776305210?e=1765411200&v=beta&t=Cv_OHsN-E-29HtCIMbQDONVJj1wMNAelzR5ljgbY3QY', 'https://linkedin.com/in/adebbah', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('07f82541-6cb3-4195-bde4-69be90c281b1', 'https://www.linkedin.com/sales/lead/ACwAAAOb0J8BFTpob4ctSm7Q6PkfIRXGrU76KEc,NAME_SEARCH,CvA8', 'Paul', 'Tyan', 'Head of Product, AI', 'Paris, Île-de-France, France', 'Tiime', '11283922', (SELECT id FROM entreprises WHERE company_id_linkedin = '11283922' LIMIT 1), 1, 1, 1, 1, 'ACwAAAOb0J8BFTpob4ctSm7Q6PkfIRXGrU76KEc', '⚡️ Freelance product leader / CPO with 10+ years of experience in startups and entrepreneurship
🤝 Product coach on career development for PMs and future PMs: https://bit.ly/paul_coaching
🚀 Ex-founder of a film music production company working in cinema, TV and advertising
🛠️ Ex-Google with an engineering and business background', 'Leading product strategy of GenAI and LLM initiatives to simplify accounting for entrepreneurs and streamline workflows for accountants.
• Built roadmaps and prioritized opportunities, acting as a bridge between leadership, product, engineering, and business teams, to align on strategy, scope, delivery and stakeholder expectations.
• Managed 3 PMs on AI products from scoping and prioritization to user testing and design reviews on several tools such as an AI agent for entrepreneurs and an LLM email generator for accountants.
• Introduced data-driven prioritization by designing and tracking KPIs (revenue, time savings, etc.)
• Oversaw strategic partnerships and vendor benchmarks (Dust, Artefact, Snowflake, Databricks).
• Setup governance and knowledge-sharing practices such as team rituals and documentation standards.', '2nd', False, False, 12, 'https://media.licdn.com/dms/image/v2/D5603AQEoS6QlRPVEJw/profile-displayphoto-crop_800_800/B56Zo5oQhFI0AI-/0/1761903446760?e=1765411200&v=beta&t=72rWNY2ZYP03sRgs-uyJyOS1YidiF12UlmcR9n7aHP0', 'https://linkedin.com/in/paultyan', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('97f243f1-55bd-482c-bb21-9ed28ed4d222', 'https://www.linkedin.com/sales/lead/ACwAAAOfG-4BAOO2ZujKTueeb0bOENcc6I_ikHY,NAME_SEARCH,Yeep', 'Charles', 'Pasquier', 'Head of Sales', 'Paris, Île-de-France, France', 'Wiztrust', '9307217', (SELECT id FROM entreprises WHERE company_id_linkedin = '9307217' LIMIT 1), 0, 7, 0, 7, 'ACwAAAOfG-4BAOO2ZujKTueeb0bOENcc6I_ikHY', 'B2B SaaS sales professional with 15+ years of experience in driving revenue growth and leading high-performing teams. Proven expertise in managing complex sales cycles, implementing scalable strategies, and delivering measurable results in fast-paced tech environments. Adept at aligning sales processes with business goals to accelerate recurring revenue and optimize customer retention. Recognized as a top performer and strategic contributor within SaaS organizations.', 'As a software publisher specialized in digital marketing, press and public relations, we help listed companies and financial services to achieve a common objective : exploit the potential of their content and improving their results.
We provide our customers with 100% online platforms where information is produced, verified, validated and analysed.', '2nd', True, True, 12, 'https://media.licdn.com/dms/image/v2/C4E03AQHAkoaItoDGvA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1651751313369?e=1765411200&v=beta&t=FIg5WkzNyQymKv2yMgL9iw8o4OSRpgQd76U_Vq8yofU', 'https://linkedin.com/in/charles-pasquier-57a42118', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('940be8db-0823-459d-8482-1d060c573ac2', 'https://www.linkedin.com/sales/lead/ACwAAAOr4WgB8wrQzjXGWFdilMxu9hbn-xR8oIo,NAME_SEARCH,Qiyg', 'Alexandre', 'Sutra', 'Head of Community', 'France', 'crème de la crème', '9478402', (SELECT id FROM entreprises WHERE company_id_linkedin = '9478402' LIMIT 1), 0, 5, 0, 5, 'ACwAAAOr4WgB8wrQzjXGWFdilMxu9hbn-xR8oIo', 'Thank you for visiting my profile!

I’m Alexandre, a human-centric leader, community strategist and tech event organizer with a passion for forging meaningful connections and driving engagement in fast-paced environments. With over 12 years of experience in digital innovation, I’ve built and nurtured vibrant communities, organized large-scale events and developed field marketing strategies tailored to software/cloud engineers, product managers and decision-makers.

I’ve cultivated a cohesive career while maintaining strong language skills in English and Spanish. Fueled by a constant movement mindset, the creation of Community Guy, my freelance activities, have ignited a personal ambition rooted in authenticity, empathy and autonomy.

--
My expertise spans:
➡ Community Building: Designing and animating tech and product communities to foster collaboration, knowledge-sharing, engagement and innovation.
➡ Event Management: Leading high-impact B2B & corporate events, with a focus on inclusion and real-world outcomes.
➡ Field Marketing : Turning complex ideas into clear, engaging stories to connect with audiences and drive action.

Let’s connect if you’re passionate about building meaningful engagement, driving change or creating spaces where people and ideas thrive.', NULL, '2nd', False, False, 101, 'https://media.licdn.com/dms/image/v2/D5603AQHwjJh4dUzGRg/profile-displayphoto-shrink_800_800/B56ZaBJePIGUAc-/0/1745923466986?e=1765411200&v=beta&t=YlDqgyJzRUa1RJmOg4-OOAcAG1_6ItYdf7weue9yZZs', 'https://linkedin.com/in/sutraalexandre', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('5694bf62-91c0-440c-8065-020bb637a34e', 'https://www.linkedin.com/sales/lead/ACwAAAPaF2QBE46CvaMwVeTvhMmapEe05JIlufo,NAME_SEARCH,YAew', 'Noémie', 'Marceau', 'Head of new business', 'Paris, Île-de-France, France', 'Agence NéNo', '10304437', (SELECT id FROM entreprises WHERE company_id_linkedin = '10304437' LIMIT 1), 1, 3, 4, 3, 'ACwAAAPaF2QBE46CvaMwVeTvhMmapEe05JIlufo', 'Skills
- Demonstrated ability to function as a team player and strong member of a highly motivated and integrated sales management team.
- Good knowledge of the HR partnership Market, HR Market and competitors..
- Good interpersonal skills with the ability and confidence to communicate with people at all levels.
- Good organisational skills with the ability to prioritise tasks.
- Knowledge and understanding of the sales process to drive partners to be profitable.

Awards

Glassdoor: EMEA GRIT Awards 2020
CornerJob: Gamelearn – Pacific – Leadership Training – Major 2018 
Viadeo: Customer Centric Selling® - Major 2015 – Trainer : Jean-Marc Bellot
', NULL, '2nd', False, False, 13, 'https://media.licdn.com/dms/image/v2/D4E03AQGujDUkg03yWA/profile-displayphoto-shrink_800_800/B4EZbYNQWPHYAc-/0/1747384078415?e=1765411200&v=beta&t=pqHWWRJp91K1mgM7lGPemN9sFTt54L1Pu5PebqJqETo', 'https://linkedin.com/in/no%C3%A9mie-marceau', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('5ca33d36-c6f2-42d5-b97f-1081e6d109ee', 'https://www.linkedin.com/sales/lead/ACwAAATHyJ8Bpmu_F7Ud-WPpHry44Yqp-Q5wJNw,NAME_SEARCH,hvZD', 'Julien', 'Saagian', 'Head Of Strategic Partnerships (Channel partners)', 'Paris, Île-de-France, France', 'Gojob - Aglaé', NULL, (SELECT id FROM entreprises WHERE company_id_linkedin = NULL LIMIT 1), 0, 4, 0, 4, 'ACwAAATHyJ8Bpmu_F7Ud-WPpHry44Yqp-Q5wJNw', 'Passionné par les nouvelles technologies, j''ai évolué dans différentes Directions Commerciales, avec une conviction profonde : aider et accompagner les équipes Sales à développer leur potentiel.

Je suis orienté clients et résultats .
J''aime particulièrement évoluer dans un contexte saint et enrichissant.', '🚀 En quelques années, nous avons multiplié nos revenus par 7 et atteint la rentabilité.
Aujourd’hui, Gojob s’impose comme un leader de sa catégorie.

🇫🇷 Fier d’être membre de la French Tech Next40 et de porter une vision ambitieuse pour le recrutement.

🤖 Grâce à notre techno et à notre IA souveraine, nous rendons le recrutement plus simple, plus rapide et plus efficace – au service des entreprises comme des candidats.

👉 Et ce n’est que le début.', '2nd', False, False, 26, NULL, 'https://linkedin.com/in/julien-saagian-167a3922', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('4bb101cd-a2b7-4df5-9c6a-451109004732', 'https://www.linkedin.com/sales/lead/ACwAAAWeHzIB7c3s98UYigFsxpRsdD7gzsRuZHc,NAME_SEARCH,wThB', 'Margarita', 'Dos Santos', 'Head of Product, Tech & Data', 'Paris, Île-de-France, France', 'ALGONIS', '2564202', (SELECT id FROM entreprises WHERE company_id_linkedin = '2564202' LIMIT 1), 0, 4, 0, 4, 'ACwAAAWeHzIB7c3s98UYigFsxpRsdD7gzsRuZHc', '- 13 years of experience in Tech and Product Management roles, with a proven track record in leadership positions.
- Experience in managing cross-functional teams of 20+ members (20+ PM, UX, QA, Developers, DevOps, Data Scientists, Data Engineers)
- Experienced in managing both scale-up growth and down-sizing transitions, ensuring continuous alignment with evolving business goals.
- Versatile professional with experience in startups, mid-sized companies (ETIs), and large corporations, showcasing a strong adaptability to different contexts.
- Deep expertise in the insurance, and medtech industries, navigating complex and regulated environments.
- Skilled in balancing strategy and execution, leading teams to deliver impactful, data-driven solutions.
- Fluent English - IELTS 7.5', '▫️ Accompagnement stratégique et opérationnel dans la restructuration et le management d’une équipe de 10 personnes (PM et développeurs)
▫️ Transformation du modèle opérationnel de delivery (roadmap produit, agilité, gouvernance). 
▫️ Mise en place d’une approche orientée impact et accompagnement sur la discovery', '2nd', False, False, 8, 'https://media.licdn.com/dms/image/v2/D4E03AQEIDEMAowak_A/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1709115283801?e=1765411200&v=beta&t=RmQi9UnYpdTUj_AtH7nyvUB4drN_-rPXx2G2Q0WpRJY', 'https://linkedin.com/in/margarita-dos-santos', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('5eaddc15-9793-41fa-86e6-9706350499e5', 'https://www.linkedin.com/sales/lead/ACwAAAaTj3ABXXtFdKurRMSlQQI8LA8yAYJ-K-Q,NAME_SEARCH,diV0', 'Eric', 'Maizier', 'Head of Product', 'France', 'Fortuneo', '82253', (SELECT id FROM entreprises WHERE company_id_linkedin = '82253' LIMIT 1), 3, 3, 7, 2, 'ACwAAAaTj3ABXXtFdKurRMSlQQI8LA8yAYJ-K-Q', NULL, 'Head of Product sur périmètre vente (site public, parcours d''EER / souscriptions, plateform) et gestion client (app Mobile, espace client WEB)', '2nd', False, False, 11, 'https://media.licdn.com/dms/image/v2/D4E03AQFnYJWOifhbPA/profile-displayphoto-crop_800_800/B4EZgc9sVzGUAM-/0/1752832591604?e=1765411200&v=beta&t=2sLA-vpy4RE75_CDaS8YOt1LZukdaH0jS6I2ngdgbjA', 'https://linkedin.com/in/eric-maizier-700b4a30', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('474249f0-67f8-4139-bf90-b204df99fb1a', 'https://www.linkedin.com/sales/lead/ACwAAAcuJosBqGfbHMZD_AIsUIAJOA5ri8i5B4E,NAME_SEARCH,AWV4', 'Camille', 'Biau', 'Head of Communication Group', 'Paris, Île-de-France, France', 'Babilou Family', '37205001', (SELECT id FROM entreprises WHERE company_id_linkedin = '37205001' LIMIT 1), 1, 9, 1, 9, 'ACwAAAcuJosBqGfbHMZD_AIsUIAJOA5ri8i5B4E', NULL, NULL, '2nd', False, False, 10, 'https://media.licdn.com/dms/image/v2/D4E03AQH8jnkn4YCogA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1682672562290?e=1765411200&v=beta&t=yQ5ZOerJzJdu8diyTz2e4d3MuSeUiGk1LUDfWSLPN1s', 'https://linkedin.com/in/camille-biau-68b41534', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('e9a49635-007e-4963-b74f-fa7e108d8a19', 'https://www.linkedin.com/sales/lead/ACwAAAiwwq0BSsIq0ymfwqEdGy2-QH4FvlZhw4E,NAME_SEARCH,OZAF', 'Charlotte', 'Lampe', 'Group Head of Marketing', 'France', 'Babilou Family', '37205001', (SELECT id FROM entreprises WHERE company_id_linkedin = '37205001' LIMIT 1), 1, 8, 1, 8, 'ACwAAAiwwq0BSsIq0ymfwqEdGy2-QH4FvlZhw4E', NULL, NULL, '2nd', False, False, 3, 'https://media.licdn.com/dms/image/v2/D4E03AQHxXN-a3XdnBQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1707319900872?e=1765411200&v=beta&t=fOXGY4sBRgyUPUaGmPKyh-TdDEyHjKO8Adlv0cpqcpo', 'https://linkedin.com/in/charlottelampe', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('46fa98a5-3a99-4ad6-9652-d90c5f474f32', 'https://www.linkedin.com/sales/lead/ACwAAAmkslUB9nqtTDCYDDjP7awwGR9upRf072E,NAME_SEARCH,OtTi', 'Jerry', 'Fuzellier', 'Head of Data', 'Créteil, Île-de-France, France', 'New Planet Media', '129570', (SELECT id FROM entreprises WHERE company_id_linkedin = '129570' LIMIT 1), 1, 9, 13, 8, 'ACwAAAmkslUB9nqtTDCYDDjP7awwGR9upRf072E', 'Touche à tout et polyvalent, je prends plaisirs à rester dans le cœur du réacteur et trouver les solutions les plus efficientes en utilisant un minimum de ressources, qu''elles soient matérielles ou humaines.', '- Pilotage de l’équipe Data et supervision de projets stratégiques en gestion, transformation et visualisation des données.
- Mise en place de Mage.ai afin d''automatiser et optimiser la gestion des pipelines de données des clients, permettant ainsi de traiter efficacement de grands volumes de données via leur ingestion, transformation et consolidation. Par exemple, un pipeline a été développé pour analyser les interactions des utilisateurs avec les contenus web, ce qui a permis d’identifier leurs centres d’intérêt. Cette solution a favorisé la personnalisation des campagnes newsletters, amélioré la segmentation des audiences et renforcé l’efficacité publicitaire grâce à un ciblage comportemental plus précis.
- Conception et déploiement d’un Data Warehouse centralisé pour un client du monde médical, modernisant la gestion de leurs données et leur exploitation via Metabase, tout en intégrant des sources variées (Mysql, HFSQL, Oracle, PostgreSQL).', '2nd', False, False, 2, 'https://media.licdn.com/dms/image/v2/C4D03AQH6JiNm3xKdWQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1582833416211?e=1765411200&v=beta&t=axqs5Jl7mw7JlGTD35Cxp_6WIxoz2rtRkus8n9Ro9Qk', 'https://linkedin.com/in/jerry-fuzellier', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('6b1843cf-90a3-4619-b5d8-d9625410fedc', 'https://www.linkedin.com/sales/lead/ACwAAAxy6zQBWEj6XsIonoupLI_P-Sr8vUbn9e0,NAME_SEARCH,hUxH', 'Sébastien', 'BERARD', 'Advanced Data Services - Head of projects and innovation', 'Petit-Mars, Pays de la Loire, France', 'Euronext', '3829', (SELECT id FROM entreprises WHERE company_id_linkedin = '3829' LIMIT 1), 6, 2, 6, 2, 'ACwAAAxy6zQBWEj6XsIonoupLI_P-Sr8vUbn9e0', NULL, NULL, '2nd', False, False, 11, 'https://media.licdn.com/dms/image/v2/D4E03AQHx67RO05RI3w/profile-displayphoto-crop_800_800/B4EZjwhFhVGUAM-/0/1756381862778?e=1765411200&v=beta&t=aQ1Ul5ih4On0OdhqCu4knyESQZRPtr8qLb_7-4HQY_w', 'https://linkedin.com/in/sebastienberard', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('b3348a6a-f4e1-4bed-8de1-60f3df9e55d6', 'https://www.linkedin.com/sales/lead/ACwAAA0MNc4Bg7rN-xS5wQqUUmL21Fnld2gMxIY,NAME_SEARCH,FYv6', 'Alexia', 'Nicolas', 'Head of marketing', 'Courbevoie, Île-de-France, France', 'Babilou Family', '37205001', (SELECT id FROM entreprises WHERE company_id_linkedin = '37205001' LIMIT 1), 0, 11, 0, 11, 'ACwAAA0MNc4Bg7rN-xS5wQqUUmL21Fnld2gMxIY', NULL, NULL, '2nd', False, False, 18, 'https://media.licdn.com/dms/image/v2/C4D03AQFcRjMhYhE8_w/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1569784138133?e=1765411200&v=beta&t=MVrWZHdaVtn65KGBFdlWGz1ux2csrvPSBk9YBHLxTD0', 'https://linkedin.com/in/alexia-nicolas-69238861', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('6a5df204-a200-4903-8d69-315cb00e75aa', 'https://www.linkedin.com/sales/lead/ACwAAA1zQG8B_nzz82B0EnjzWE2wYdvsxsYFzOg,NAME_SEARCH,VXxH', 'Franck', 'Frefield-Beilborn', 'Head of Corporate & In-House Communications', 'France', 'Axens', '24149', (SELECT id FROM entreprises WHERE company_id_linkedin = '24149' LIMIT 1), 2, 11, 3, 4, 'ACwAAA1zQG8B_nzz82B0EnjzWE2wYdvsxsYFzOg', 'Quadrilingual fluency in French, English, Spanish and Italian

Multicultural with extensive Corporate (External communications, PR), HR (Internal Communication, Employer Brand) and C&SR Communication experiences  

A solid track record in a variety of sectors and business models : Naval Defense, Building and Civil Engineering, Services, Oil & Gas

Experienced in Change Management with organisations of all sizes ; start-up, SME, large matrix corporations', NULL, '2nd', False, False, 14, 'https://media.licdn.com/dms/image/v2/C5603AQFp28rFecrSiA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1579269030998?e=1765411200&v=beta&t=qJ5zeHsDVZiQvpsftvi80uatCnLOacYZMFLsnizY3aU', 'https://linkedin.com/in/franck-frefield-beilborn', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('83c081e4-1a6d-4717-b820-98b99210897d', 'https://www.linkedin.com/sales/lead/ACwAABFHNTMBEC-ZjQZybtEbTfYl60WI-yh5XLM,NAME_SEARCH,EUb4', 'Claire', 'Beisson', 'Head of department, Global experience', 'St.-Denis, Île-de-France, France', 'Groupe Randstad France', '382028', (SELECT id FROM entreprises WHERE company_id_linkedin = '382028' LIMIT 1), 1, 2, 12, 8, 'ACwAABFHNTMBEC-ZjQZybtEbTfYl60WI-yh5XLM', '


', 'Management de l''équipe Expérience client & parcours digitaux (8 direct reports)
- expérience et satisfaction client : analyse des parcours, enquêtes NPS, verbatim, recommandations d’amélioration.
- CRM & marketing relationnel : campagnes emailings, marketing automation, segmentation, fidélisation et engagement client.
- optimisation des parcours digitaux : UX, CRO, testing et amélioration continue.
Le tout data-driven : structuration, analyse et exploitation de la data, dashboards et monitoring des KPIs', '2nd', False, False, 12, 'https://media.licdn.com/dms/image/v2/C5603AQFtjAKBu82IQw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1604574608566?e=1765411200&v=beta&t=bfFSeNKy0LeQBtkhOBsBXjk1dayhH8aFja5KqceScz8', 'https://linkedin.com/in/claire-beisson', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0),
)))%2C(type%3ACONNECTION_OF%2Cvalues%3AList((id%3AACwAAAJ992kBFkJUgchg3AraLoZ8dgSy1jqta5k%2Ctext%3AJulien%2520Bechkri%2CselectionType%3AINCLUDED)))))&sessionId=V52i5YpTSiiD%2BgjtVpY2mQ%3D%3D&viewAllFilters=true'),
('0dab3183-5268-4d1c-81d6-1fae260bd235', 'https://www.linkedin.com/sales/lead/ACwAABNDxFsBtsCpk5ntt6_M6LuH5IQtNyIPuE8,NAME_SEARCH,8KkS', 'Claire', 'Ernewein', 'Head Of CRM', 'St.-Denis, Île-de-France, France', 'Wamiz', '2948090', (SELECT id FROM entreprises WHERE company_id_linkedin = '2948090' LIMIT 1), 1, 10, 1, 10, 'ACwAABNDxFsBtsCpk5ntt6_M6LuH5IQtNyIPuE8', '✨ Le marketing, pour moi, c’est un savant mélange de données, de créativité et d’histoires humaines.Aujourd’hui Head of CRM chez Wamiz, le média #1 du bien-être animal, je conçois et pilote des stratégies relationnelles pour activer, fidéliser et engager des communautés exigeantes.Avec plus de 10 ans d’expérience en marketing digital, dont 5 ans dédiés au CRM, j’ai évolué dans des environnements variés — startups, PME et grands groupes — et des secteurs aussi riches que le cinéma, la cosmétique, le bricolage ou l’aéronautique.J’ai eu la chance de collaborer avec de belles marques comme L’Oréal, Air France, Free, Randstad ou Monsieur Bricolage, sur des projets alliant stratégie, data et créativité.🌟 Ce qui me motive : comprendre les comportements, imaginer des expériences clients sur mesure et transformer les insights en actions concrètes.🔹 Mes forces : enthousiasme, organisation, curiosité et esprit analytique.💬 Toujours partante pour échanger autour du CRM, de la fidélisation ou de la transformation marketing !', 'En tant que Head of CRM pour Wamiz (média #1 en matière de bien être animal, disponible dans 7 pays à travers le continent européen) mon champs d''action touche aussi bien la partie purement opérationnelle que stratégique.

Objectif : créer une offre CRM personnalisée et sans couture.

> Définition et mise en place de campagnes d''acquisitions internationales (FR/UK/ES/PL/NL/IT/DE)
> Définition et mise en place de campagnes emailing standards (dont un projet de refonte global sur les 7 marchés)
> Définition et mise en place de campagnes emails automatisées (onboarding, antichurn, programme d''aide à l''éducation des animaux de moins de 1 an ou des futurs pet parents)
> Mise en place d''un nouvel outil CRM (formation des parties prenantes pour une prise en main efficace sur les 7 marchés)
> Débugage avec l''équipe IT (équipe internationale basée à Barcelone)
> Management de partenaires extérieurs et/ou internationaux (agences, collaborateurs internes)
> Création et mise en place de tableaux de suivi (sur mixpannel et/ou big query)
> Management d''équipe', '2nd', False, False, 18, 'https://media.licdn.com/dms/image/v2/D4E03AQHW26K2FK37Qg/profile-displayphoto-crop_800_800/B4EZnJQCikGUAI-/0/1760018050569?e=1765411200&v=beta&t=B_1-KfcO4w_T6lUXKTC77UX-B4nKbpbS1O1B-Ur-KbU', 'https://linkedin.com/in/claireernewein', 'https://www.linkedin.com/sales/search/people?query=(recentSearchParam%3A(id%3A5264073940%2CdoLogHistory%3Atrue)%2Cfilters%3AList((type%3ACURRENT_COMPANY%2Cvalues%3AList((id%3Aurn%253Ali%253Aorganization%253A10152136%2Ctext%3ADigilityx%2CselectionType%3AEXCLUDED%2Cparent%3A(id%3A0)
ON CONFLICT (linkedin_url) DO NOTHING;
