INSERT INTO entreprises (company_name, company_id_linkedin, company_location) VALUES
('OXYL', '48156274', 'Arcueil, Île-de-France, France'),
('Onepoint', '816396', 'Paris, Île-de-France, France'),
('La Minut''Rit - Conciergerie d''entreprise', '5076907', 'Lyon, Auvergne-Rhône-Alpes, France'),
('Microsoft', '1035', 'Redmond, Washington, United States'),
('FEDERALE Assurance-Verzekering', '114306', 'Brussels, Brussels Region, Belgium'),
('SUB ROSA', '106085344', 'Paris, Île-de-France, France'),
('Sage', '2802', 'Newcastle Upon Tyne, England, United Kingdom'),
('Air Liquide', '3818', 'Paris, Île-de-France, France'),
('RedPill SAS', '10372256', 'Paris, Île-de-France, France'),
('Rexel', '6637', 'Paris, Île-de-France, France'),
('Pale blue dot', '56443553', 'Malmo, Skåne County, Sweden'),
('Fondation Inria', '18559105', 'Paris, Île-de-France, France'),
('JC Conseil Formation Coaching', '78124000', 'Toulouse, Occitanie, France'),
('EUROGROUP CONSULTING', '7238', 'Courbevoie, Île-de-France, France'),
('Groupe Crédit Agricole', '7467', 'Montrouge, Île-de-France, France'),
('DEEP', '104480454', 'Luxembourg, Luxembourg, Luxembourg'),
('Mews Partners', '45451', 'Paris, Île-de-France, France'),
('Your.Online', '28131403', 'Amsterdam, North Holland, Netherlands'),
('Sopra Steria', '3054', 'Paris, Île-de-France, France'),
('ekino', '1707956', 'Pantin, Île-de-France, France'),
('Cegid', '162946', 'Le Puy, Nouvelle-Aquitaine, France'),
('Paris Business Angels', '2270760', 'Paris, Île-de-France, France'),
('Désclic', '53410291', 'Évreux, Normandy, France'),
('Ministry of Education, Youth and Sports, and Ministry of Higher Education, Research and Innovation', '64597705', 'Paris, Île-de-France, France'),
('Abu Dhabi Investment Authority (ADIA)', '10742', 'Abu Dhabi, Abu Dhabi Emirate, United Arab Emirates'),
('Ubisoft Film & Television Paris', '28843214', 'Saint-Mandé, Île-de-France, France'),
('SAP', '1115', 'Walldorf, Baden-Württemberg, Germany'),
('XPR-IT', '97387', 'Paris, Île-de-France, France'),
('Infor', '1711', 'New York, New York, United States'),
('IFS', '164301', 'Linköpings kommun, Östergötland County, Sweden'),
('Metaware Technologies', '254169', NULL),
('Teladoc Health', '128505', 'Purchase, New York, United States'),
('Aeris IoT SaaS', '54080', 'San Jose, California, United States'),
('Opensee', '10972518', 'Puteaux, Île-de-France, France'),
('LUCYA Group', '6759564', 'Paris, Île-de-France, France'),
('Saint-Gobain', '2981', 'Courbevoie, Île-de-France, France'),
('Volante Technologies', '127394', 'Jersey City, New Jersey, United States'),
('DealRelations', '15246691', NULL),
('KPMG France', '1848155', 'France'),
('OCP Group', '165281', 'Casablanca, Casablanca-Settat, Morocco'),
('Confluent', '88873', 'Mountain View, California, United States'),
('maurel-conseil.fr', '68493965', NULL),
('Niji', '13435', 'Issy-les-Moulineaux, Île-de-France, France'),
('Dolce Brooklyn', '10794534', 'Brooklyn, New York, United States'),
('Renesas Electronics', '934588', 'Tokyo, Tokyo, Japan'),
('Memo Bank', '11089856', 'Paris, Île-de-France, France'),
('Wallester', '11290718', 'Tallinn, Harjumaa, Estonia'),
('Morgan Stanley', '497017', 'New York, New York, United States'),
('ActiveViam', '85029', 'New York, New York, United States'),
('La Forge', '20151827', 'Paris, Île-de-France, France'),
('Avanade', '3033', 'Seattle, Washington, United States'),
('ARC Europe France', '10519699', 'France'),
('Neolium', '5285706', 'Lyon, Auvergne-Rhône-Alpes, France'),
('VISEO', '22294', 'Boulogne-Billancourt, Île-de-France, France'),
('CHANEL', '162993', 'London, England, United Kingdom'),
('SIWAY', '1550059', 'Paris, Île-de-France, France'),
('Bengs', '4786534', 'Paris, Île-de-France, France'),
('EY', '1073', 'London, England, United Kingdom'),
('Velvet Consulting', '291607', 'Levallois-Perret, Île-de-France, France'),
('L''Oréal', '1662', 'Clichy, Île-de-France, France'),
('saegus', '6406379', 'Paris, Île-de-France, France'),
('APGAR', '3354890', 'Neuilly-sur-Seine, Île-de-France, France'),
('Publicis Sapient France', '36120395', 'Paris, Île-de-France, France'),
('Consultant', '15214453', 'Ardington, England, United Kingdom'),
('Dell Technologies', '15088102', 'Round Rock, Texas, United States'),
('Malakoff Médéric', '34644526', 'Paris, Île-de-France, France'),
('THALES DMS FRANCE SAS', '49664493', 'Élancourt, Île-de-France, France'),
('kaiserkraft', '777662', 'Stuttgart, Baden-Württemberg, Germany'),
('PONANT', '1125351', 'Marseille, Provence-Alpes-Côte d''Azur, France'),
('Publicis Sapient', '10801655', 'Boston, Massachusetts, United States'),
('Netwrix Corporation', '455932', 'Frisco, Texas, United States'),
('La Poste Groupe', '164661', 'Paris, Île-de-France, France'),
('Lefebvre Dalloz', '71742343', 'Courbevoie, Île-de-France, France'),
('TRIDO', '27054458', 'Paris, Île-de-France, France'),
('ADDIS Technologies', '5318810', 'Paris, Île-de-France, France'),
('Sena', '102795913', 'Remote, Oregon, United States'),
('ProjectiveGroup', '74947332', 'Machelen, Flemish Region, Belgium'),
('Reward Solution', '101129131', 'Paris, Île-de-France, France'),
('Hyland', '10043', 'Westlake, Ohio, United States'),
('Swiss Life France', '3260928', 'Levallois-Perret, Île-de-France, France'),
('Accuracy', '436400', 'Paris, Île-de-France, France'),
('ISITEC International', '472435', 'Vourles, Auvergne-Rhône-Alpes, France'),
('COMPANION', '98689431', 'Paris, Île-de-France, France'),
('Embrace', '10173173', 'Boulogne-Billancourt, Île-de-France, France'),
('TOULON', '22654235', 'Brussels, Brussels Region, Belgium'),
('Livosphere', '5131590', 'Labretonie, Nouvelle-Aquitaine, France'),
('Startup Madeira', '15230899', 'Funchal, Madeira Island, Portugal'),
('Benefit Cosmetics', '19295', 'San Francisco, California, United States'),
('Agile Enterprise Partner', '10362387', 'Croissy-sur-Seine, Île-de-France, France'),
('Volvo Car France', '10288664', 'Nanterre, Île-de-France, France'),
('Reed Midem', '12857', 'Puteaux, Île-de-France, France'),
('Workiva', '732400', 'Ames, Iowa, United States'),
('MLOGICA, LLC', '72027', 'Las Vegas, Nevada, United States'),
('Eau de Paris', '1169320', 'Paris, Île-de-France, France'),
('Regata', '72503187', 'Nantes, Pays de la Loire, France'),
('Crédit Agricole CIB', '2579', 'St.-Raphaël, Provence-Alpes-Côte d''Azur, France'),
('Societe Generale', '1691', 'Paris, Île-de-France, France'),
('Banque de France', '12206', 'Paris, Île-de-France, France'),
('CNP Assurances', '14322', 'Issy-les-Moulineaux, Île-de-France, France'),
('Cloud Data Engine (CDE)', '100248059', 'Paris, Île-de-France, France')
ON CONFLICT (company_id_linkedin) DO NOTHING;